---
name: Publish Resume & PDF
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install resume-cli globally
        run: npm install -g resume-cli
      - name: Install theme with legacy peer deps
        run: npm install jsonresume-theme-professional --legacy-peer-deps
      - name: list jsonresume-theme-professional files
        run: ls -la /home/runner/work/uko-json-resume/uko-json-resume/node_modules/jsonresume-theme-professional/src/ui
      - name: Check theme structure
        run: |
          echo "Listing theme folder contents:"
          ls -la node_modules/jsonresume-theme-professional
          echo "Listing theme src folder contents:"
          ls -la node_modules/jsonresume-theme-professional/src
      - name: Generate PDF Resume
        run: resume export resume.pdf --theme ./node_modules/jsonresume-theme-professional/src --resume resume.json
      - name: Prepare files for Gist update
        id: prep
        run: |
          touch resume.pdf \
          echo "Reading JSON file..."
          JSON_CONTENT=$(jq -c . resume.json)
          echo "Encoding PDF file..."
          PDF_CONTENT=$(base64 resume.pdf | tr -d '\n')

          echo "JSON_CONTENT=$JSON_CONTENT" >> $GITHUB_ENV
          echo "PDF_CONTENT=$PDF_CONTENT" >> $GITHUB_ENV
        shell: bash
      - name: Update Gist with Resume and PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_PAT_TOKEN }}
        run: |
          curl -X PATCH \
          -c, --cookie-jar \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          -d "$(jq -n --arg json "${{ steps.prep.outputs.json }}" --arg pdf "${{ steps.prep.outputs.pdf }}" '{
          files: {

          "resume.json": { content: $json },

          "resume.pdf": { content: $pdf }
           }
          }')" \
              https://gist.github.com/malachi43/51c8c85804e98a02dd0271e3a857a313
